service: vision
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  environment: 
    BUCKET_NAME: ${env:BUCKET_NAME}
  
  iam:
    role:
      name: role-for-computer-vision-app
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource:
            - arn:aws:s3:::${env:BUCKET_NAME}/*
        - Effect: Allow
          Action:
            - rekognition:DetectLabels
            - rekognition:DetectFaces
          Resource: "*"

resources:
  Resources:
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:BUCKET_NAME}


functions:
  health:
    handler: routes/health.health
    events:
      - httpApi:
          path: /
          method: get
  v1Description:
    handler: routes/v1.v1_description
    events:
      - httpApi:
          path: /v1
          method: get
  v2Description:
    handler: routes/v2.v2_description
    events:
      - httpApi:
          path: /v2
          method: get