service: api-tts
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  health:
    handler: routes/health.health
    events:
      - httpApi:
          path: /
          method: get
  v1Description:
    handler: routes/v1.v1_description
    events:
      - httpApi:
          path: /v1
          method: get
  v2Description:
    handler: routes/v2.v2_description
    events:
      - httpApi:
          path: /v2
          method: get
      
